env:
  browser: true
  commonjs: false
  es2021: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
  - 'plugin:prettier/recommended'
  - 'plugin:jsdoc/recommended'
plugins:
  - prettier
  - require-sort
  - jsdoc
  - disable
  - import
overrides:
  - files:
      - '*.js'
    settings:
      disable/plugins:
        - jsdoc
parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  babelrc: false
  configFile: false
  ecmaVersion: latest
  sourceType: module
  presets: ['@babel/preset-env']
processor: 'disable/disable'
rules:
  'require-sort/require-sort': [warn,
    {
      ignoreCase: false,
      ignoreDeclarationSort: false,
      ignorePropertySort: false,
      propertySyntaxSortOrder: ["none", "multiple", "single"],
    }
  ]
  no-param-reassign: ['error', { 'props': false }]
  sort-imports: [warn,
    {
      ignoreCase: false,
      ignoreDeclarationSort: false,
      ignoreMemberSort: false,
      memberSyntaxSortOrder: ["none", "all", "multiple", "single"],
      allowSeparatedGroups: false
    }
  ]
