env:
  browser: true
  commonjs: false
  es2021: true

extends:
  - 'airbnb-base'
  - 'eslint:recommended'
  - 'plugin:jsdoc/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:regexp/recommended'
plugins:
  - import
  - jsdoc
  - prettier
  - regexp

overrides:
  - files:
      - '*.js'

parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  babelrc: false
  configFile: false
  ecmaVersion: latest
  sourceType: module
  presets:
    - '@babel/preset-env'

rules:
  no-param-reassign:
    - error
    - props: false
  sort-imports:
    - warn
    - ignoreCase: false
      ignoreDeclarationSort: false
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - multiple
        - single
      allowSeparatedGroups: false
